### ISSUE TITLE
DatePicker: testClearButton test failing

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#101]
```
DatePicker004Test.testClearButton:172->assertDate:218 Year 2021 expected but DatePicker panel contained:August 2020
```

I cannot get this to happen locally. And since its just JS code and not any AJAX I don't know why it would be a timing issue.  Can anyone else please run DatePicker004 locally?

**Comment by christophs78** [comment]
It´s not Mac-specific.
Happend now once on my Windows-Dev-notebook under high load.

**Comment by christophs78** [comment]
Is this maybe related to https://github.com/primefaces/primefaces/commit/95b7347092f0a6affecee223c58f1d78e37394df?
(Not sure, just asking.)

It currently fails on my windows-dev-notebook with Chrome and Firefox. Even when i only run this single test.

**Comment by melloware** [comment]
OK let me dig deeper.   Its passing right now on my Windows box. And yes that is what this test is testing that ticket.  When you press Clear it should reset the Date to null and the popup to NOW including the time fields.

**Comment by melloware** [comment]
If you step through the debugger does it pass?

**Comment by christophs78** [comment]
We need to update PrimeFaces-version to 10.0.0 in pom.xml.

But even after doing this on my-dev-notebook:
![image](https://user-images.githubusercontent.com/10461942/104814292-66a7ee00-580e-11eb-8949-ee50a9acc1fc.png)

**Comment by melloware** [comment]
Ahh I missed one spot yesterday when i was updating versions!. Fixing now

**Comment by melloware** [comment]
OK also I am testing on Safari and realized my DatePicker is failing because the default browser size is 800x600.  You fixed it for Headless mode so I added defaults of 1280x1000 for non headless mode and its fixed some of my Safari issues. 

Doing more testing on my Mac today.

**Comment by melloware** [comment]
I was able to remove all the Safari hacks from DatePicker004Test!

**Comment by christophs78** [comment]
Great!

**Comment by melloware** [comment]
@christophs78 the current tests are failing because Cagatay's changes on Friday have broken overlays like SelectOne, AutoComplete, Password etc.  I have notified PrimeTek.
