### ISSUE TITLE
Test functionality of primefaces-selenium-components

### ISSUE THREAD

**Issue by jungm** [primefaces-extensions/primefaces-integration-tests#11]
In my opinion we should not only focus on PF stability (like implementing tests for features reworked on PF 9.0, #7 for example), but also focus on the compatibility of primefaces-selenium components with the current PrimeFaces release.

Currently, we don't really know if all the components still work as intended and if they are compatible with PrimeFaces 8.0, primefaces-selenium was originally developed to work with PrimeFaces 7.0.

Tests for all of the PrimeFaces components supported by primefaces-selenium should be implemented. This could prevent bugs like https://github.com/primefaces-extensions/primefaces-selenium/issues/7 from occurring in the future.

**Comment by melloware** [comment]
Yes the focus right now is to have all the tests passing and running against 8.0. 

I put `TODO` hints on places I know the test will fail in 9.0 and need to be modified.  

So I don't quite understand the point?  The current goal is to regression test 8.0 and I thought 8.0 was a good place to start since its the latest released version no point in writing tests for 7.0 at this point.  Am I missing something?

**Comment by melloware** [comment]
Also DatePicker didn't exist in the PF Selenium suite for 7.0 so its not really a regression since I just introduced the Selenium Wrapper last week?

**Comment by jungm** [comment]
What I meant is: Tests for all the components primefaces-selenium supports should be implemented to ensure compatibility with the current PrimeFaces release. I don't want to test compatibility with PrimeFaces 7.0. Some components just probably haven't been tested since PrimeFaces 7.0.

There is currently no quick and easy way to test if primefaces-selenium's components are still working as they should. I just used https://github.com/primefaces-extensions/primefaces-selenium/issues/7 as an example that could've easily been prevented if there were tests for primefaces-selenium-components.

**Comment by melloware** [comment]
I guess you mean unit tests of the Selenium Components?  

Because I don't know how I would have caught the above error as the Selenium Wrapper was producing the correct date in my TimeZone in my browser setup.  It wasn't until it was tested in Europe that the tests failed.  So I guess you would mean a unit test?  I don't really know how else that would have been covered?

**Comment by melloware** [comment]
Forgot to mention the DatePicker test was also passing our Travis build.

**Comment by jungm** [comment]
I mean tests of all of the components to ensure they are working as they should. I'm aware that edges cases like the timezone issue I mentioned aren't easily coverable, but primefaces-selenium's components should still be tested.

**Comment by melloware** [comment]
I stil don't understand what you mean "tested"?  Tested how?  Isn't that what this Integration Tests project is for is to exercise all the functionality of the Selenium Wrapper as well as the features of the component it is wrapping?   So by definition this Integration Tests suite is the test no?

**Comment by jungm** [comment]
Exactly, this project should also be a the test suite for primefaces-selenium.
It appeared to me as if this projects goal was to implement tests for PrimeFaces as components are being changed/updated, thus I created this issue to highlight that also primefaces-selenium should be tested here.

**Comment by melloware** [comment]
OK the goal of this project is "To provide an integration and regression test suite for PrimeFaces." and to me by definition "integration" means all of the aspects of a Selenium Wrapper should be tested.  If you look at my InputMask tests I test...
- Permutations of component configuration such as `autoClear=true` and autoClear=`false` in the XHTML.
- Test all Widget methods of the component
- Test all functionality exposed by the Selenium InputMask wrapper

So as far as I am concerned InputMask is covered about as much as it can be.  The goal is to do that with 20+ other PF Selenium components.

**Comment by melloware** [comment]
That being said we are looking for PR's for people to add more comprehensive testing.  The first few tests were designed to give a roadmap on adding more and more tests!
