### ISSUE TITLE
Animation: Fix tests

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#120]
Fix all tests after Mert is done changing how components are animated.

**Comment by melloware** [comment]
Not quite sure what is going on here.  Tests are flickering. Chrome will work on my machine for DatePicker001Test then I will run it again and 2 tests will fail.  Has to be some timing issue I am not seeing.

**Comment by christophs78** [comment]
Maybe we have to wait the amount of time (0.12s) which was defined via https://github.com/primefaces/primefaces/commit/1eec431ee38b3232fe5210dd0d1566d9ab31c350#diff-79d7bf1ca7b68e744ff520715c461227d1edf5cc29abd555cf68cdaa89899b4cR150.

**Comment by christophs78** [comment]
One suggestion is to disable CSS animations for integration test: https://marcgg.com/blog/2015/01/05/css-animations-failing-capybara-specs/

**Comment by melloware** [comment]
M y thought was though 

```java
PrimeSelenium.executeScript(getWidgetByIdScript() + ".show()");
PrimeSelenium.waitGui().until(PrimeExpectedConditions.visibleAndAnimationComplete(getPanel()));
```

That the WAIT there would work but clearly for CSS is not.

**Comment by christophs78** [comment]
Maybe JS-show-function for DatePicker is currently broken. I´ll try....

**Comment by christophs78** [comment]
This is our issue:
![image](https://user-images.githubusercontent.com/10461942/107561839-50a80600-6bdf-11eb-9a21-28fbee45fc72.png)
Selenium WebDriver is wonky in terms of panel.isDisplayed()

**Comment by christophs78** [comment]
On my dev-notebook DatePicker004Test#testDateAndTimeWithHours always fails on Chrome.

I´m able to "fix" this test´s by adding some wait after setValue()
```java
datePicker.setValue(value);
PrimeSelenium.wait(100); //new code to "fix" this issue
WebElement panel = datePicker.showPanel(); // focus to bring up panel
```
I´m currently to tired from my day-job to further dig into this.

**Comment by melloware** [comment]
OK werid that the panel is displayed when its not.  Unless how it determines "Displayed" is cause by the new CSS transitions. Let me look deeper now.

**Comment by christophs78** [comment]
Got it. `DatePicker#setValue`
It shows the panel during typing. And hides it when we do `input.sendKeys(Keys.TAB);`.
When our code runs fast the hide-css-animation still runs when we call `PrimeSelenium.executeScript(getWidgetByIdScript() + ".show()");`. So show-function decides the panel is already visible. And a few moments later hide-animation is finished and DatePicker-panel is not there any more.

**Comment by christophs78** [comment]
We already have a mechanism to add https://github.com/primefaces-extensions/primefaces-selenium/blob/master/primefaces-selenium-core/src/main/resources/META-INF/resources/primefaces_selenium/pfselenium.core.csp.js to every integration-test page. We may try to use this mechanism to also inject a CSS - file which disables css-transitions introduced with https://github.com/primefaces/primefaces/commit/1eec431ee38b3232fe5210dd0d1566d9ab31c350.

**Comment by melloware** [comment]
We can try it!

**Comment by melloware** [comment]
I just checked in one fix to DatePicker in Selenium.  We were doing all that trouble to set the date but in Safari I have to call the widget  So I just switched everyone to call the widget to set the Date instead of trying to type in the box.

**Comment by melloware** [comment]
I don't think we want to disable CSS animations because anyone using PrimeSelenium to test their own PF app will just run into these same issue.  I think we need to add new check Predicate to `visibleAndAnimationComplete` like this guy is doing...

https://stackoverflow.com/a/39247375/502366

**Comment by melloware** [comment]
Also we have a config for disbaling Jquery Animations maybe we need to any another one for disableCssAnimations?

**Comment by christophs78** [comment]
> I don't think we want to disable CSS animations because anyone using PrimeSelenium to test their own PF app will just run into these same issue. I think we need to add new check Predicate to `visibleAndAnimationComplete` like this guy is doing...
> 
> https://stackoverflow.com/a/39247375/502366

Interesting. Something we may try. 
Opened a Draft-PR for PF-Selenium to disable CSS-animations on this side. But it still seems to be more complicated.
I hope we can out figure how to fix this issues this weekend.
Did not expect CSS-animations would make so much trouble on our integration-test-side.
Propably during JS-animations jQuery was active so PrimeExpectedConditions#visibleAndAnimationComplete waited until jQuery was not active any more. With CSS animations it´s different.

**Comment by melloware** [comment]
Yep I agree i think that `jquery.active==0` is what was making it work.

**Comment by christophs78** [comment]
Hm. Transition CSS-class are added asynchronous:
https://github.com/primefaces/primefaces/commit/1eec431ee38b3232fe5210dd0d1566d9ab31c350#diff-834f6bc1679ab1b3105eb2ee8fdd4d1eb5a4db4128e63760db4c1c4ebd512066R608
This may be the root cause, why we have timing-issues even with CSS-animations disabled. (transition-duration: 0s;)

**Comment by christophs78** [comment]
Maybe we have to check, that classNameStates.enter (=ui-connected-overlay-enter) is not applied to the panel any more.
This CSS-class gets attached synchronous and is removed on transitionend - event.

**Comment by melloware** [comment]
Good idea.

**Comment by melloware** [comment]
I submitted this PR: https://github.com/primefaces/primefaces/pull/6981

It doesn't fix out problem but does give us a standard way to disable CSS animations that we are already using and users are used to.

**Comment by melloware** [comment]
From all my testing this will be fixed when that PR is merged and then I just have to merge this PF selenium issue:
https://github.com/primefaces-extensions/primefaces-selenium/issues/97

Then all the tests should pass again!

**Comment by christophs78** [comment]
Very welcome news!

**Comment by melloware** [comment]
OK everything is fixed except these two tests:
```
Error:    DatePicker001Test.testHighlight:139 » NoSuchElement no such element: Unable to...
Error:    DatePicker001Test.testSelectDatePreviousMonth:103 » Timeout Expected condition...
```

However I am running with the Chrome driver locally and they are passing which tells me its some timing issue even with animations disabled.

**Comment by christophs78** [comment]
Ok. At least i´m able to reproduce this on my 8C/16T - dev-notebook when i run with junit.jupiter.execution.parallel.enabled=true.
![image](https://user-images.githubusercontent.com/10461942/107979662-3e531100-6fbf-11eb-9dc9-91a3200ca693.png)
I look into this.

**Comment by melloware** [comment]
ConfirmPopup/Dialog I fixed.  Its just the DatePicker001 tests are failing?

**Comment by christophs78** [comment]
I add some waits for DatePicker - Panel with https://github.com/primefaces-extensions/primefaces-selenium/commit/60c693959872541943d3848dccf1bc18ce8028b3. This helps.
Maybe we can come up with a better solution in future.

**Comment by melloware** [comment]
At least we fixed it for now and all tests are passing again!  Thanks for the assist.
