### ISSUE TITLE
Tomee Upgrade causing failing test

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#149]
Tomee 8.0.7 is consistently causing this failure in Chrome.

```
Errors: 
Error:    AutoComplete002Test.testSuggestions:53 » Timeout Expected condition failed: wa...
```

So not merging that PR yet.

cc @christophs78

**Comment by christophs78** [comment]
CXF was updated from 3.3.8 to 3.4.3 (as Part of TomEE 8.0.7)
error is
`SEVERE: No message body writer has been found for class org.primefaces.model.rest.AutoCompleteSuggestionResponse, ContentType: application/json`
thrown by `org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor`

**Comment by christophs78** [comment]
TomEE 8.0.6, CXF 3.3.8
![image](https://user-images.githubusercontent.com/10461942/118019935-dc097280-b359-11eb-9d90-f2a453c1ca3a.png)

**Comment by christophs78** [comment]
Probably a TomEE 8.0.7 - regression:
The following two providers (screenshot from 8.0.6) are not registered as CXF messageWriters anymore.
![image](https://user-images.githubusercontent.com/10461942/118022392-9e5a1900-b35c-11eb-9547-71d0a95727ae.png)
We should report this to the TomEE-team and so on.....

**Comment by christophs78** [comment]
https://issues.apache.org/jira/browse/TOMEE-3743

**Comment by melloware** [comment]
Thanks for reporting.  I will back up to Tomee 8.0.6 now.

**Comment by rzo1** [comment]
Thanks for reporting @christophs78 - it is indeed a regression (to be honest: the whole JAX-RS landscape is broken in **8.0.7**), which was introduced during the Jakarta EE 9.1 TCK work. Currently, were is ongoing work on fixing the regression and aim for a fast **8.0.8**. The dev@tomee.a.o list holds the relevant discussions, which I have linked in the related JIRA issue.

**Comment by melloware** [comment]
Thank you @rzo1  we will try again when 8.0.8 is released.
