### ISSUE TITLE
CI build to allow PF Selenium SNAPSHOTS

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#29]
@christophs78 creating a fix to Travis to allow the CI build to build the PF Selenium SNAPSHOT first so we can actually do a better job of testing before having to cut PF Selenium

**Comment by melloware** [comment]
OK new build works great and it will make it easier to test PR's against Travis!

**Comment by christophs78** [comment]
Thank´s for your work! Can we do something similar to run against PrimeFaces 9.0-SNAPSHOT?

**Comment by melloware** [comment]
Yep.

**Comment by melloware** [comment]
I just added building PF 9.0-SNAPSHOT as a pre step too.
