### ISSUE TITLE
CI: Nightly Build Failing

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#57]
Looks like multiple causes but this test consistently fails:
```
Timeline001Test.testSelect:57 » StaleElementReference stale element reference:...
```

It looks like the Chrome driver is 86 on GitHub OS and we were using 83 before.

**Comment by melloware** [comment]
Well it looks like the build was working 2 days ago and it was also Chrome 86.

**Comment by melloware** [comment]
OK so your PR yesterday the SelectOne all the build was passing.  Now its failing again on the nightly run with:
```
Timeline001Test.testSelect:57 » StaleElementReference stale element reference:...
```

**Comment by christophs78** [comment]
Yes. Some kind of timing issue / race condition. I will look into this the next days.
