### ISSUE TITLE
Schedule: Flickering Test

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#61]
We have another flickering test:
```
 Schedule001Test.testDateSelect:58 expected: <true> but was: <false>
```

**Comment by christophs78** [comment]
We should try
`PrimeSelenium.guardAjax(page.schedule.findElement(By.className("fc-daygrid-day-top"))).click();`

`fc-daygrid-day-top` instead of `fc-daygrid-day`

**Comment by melloware** [comment]
Let me try that.

**Comment by melloware** [comment]
That looks like it is working now.
