### ISSUE TITLE
DataList: Flickering test

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#67]
We have another flickering test that intermittently fails.

```
DataList001Test.testBasicAndPaginator:83 expected: <2> but was: <3>
```

**Comment by melloware** [comment]
@christophs78 Can you code review my potential fix? https://github.com/primefaces-extensions/primefaces-selenium/commit/8239c21728925e5dcc4b30696e263a07b4ce26e5

**Comment by melloware** [comment]
OK reverted that didn't fix it.  I did leave in the `break` though.

**Comment by christophs78** [comment]
```java
public void selectPage(Page page) {
	PrimeSelenium.guardAjax(page.getWebElement()).click();
}
```
works on my dev-machine.

I validated this by adding `Thread.sleep(1000);` to `org.primefaces.component.datalist.DataListRenderer#encodeEnd`.

**Comment by melloware** [comment]
yep but it them broke a whole bunch of Datatable tests.

**Comment by christophs78** [comment]
Ok - i´ll look at this

**Comment by christophs78** [comment]
Ah. DataTable001Test fails because
`dataTable.selectPage(1);`
does nothing when we are already on page 1.

**Comment by melloware** [comment]
Nice I wonder if we can make that method smarter if we already know what page we are on just return?

**Comment by christophs78** [comment]
Yes, i´ll look into this and check for active page.

**Comment by christophs78** [comment]
https://github.com/primefaces-extensions/primefaces-selenium/pull/54 should do it´s job

**Comment by melloware** [comment]
Nice!  I am rerunning the Integration Suite now with this fix.

**Comment by melloware** [comment]
All tests passing.  Thanks for the fix.  I think its makes the Pageable component much more flexible now too.
