### ISSUE TITLE
TabView: Flickering Test

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#69]
We had this failure last night
```
TabView002Test.test:47 expected: <1> but was: <0>
```

but it worked today. So that tells me its another timing issue.

**Comment by melloware** [comment]
Ahh so toggle tab is doing this.
```java
    public void toggleTab(int index) {
        if (ComponentUtils.hasAjaxBehavior(getRoot(), "tabChange")) {
            PrimeSelenium.guardAjax(headers.get(index)).click();
        }
        else {
            headers.get(index).click();
        }
        PrimeSelenium.waitGui().until(PrimeExpectedConditions.jQueryNotActive());
    }
```

it only does a `guard` if it has a tabChange event but not if the tabView is `dynamic=true`.

**Comment by melloware** [comment]
@christophs78 please code review this fix: https://github.com/primefaces-extensions/primefaces-selenium/commit/65ae2cf18c51011669600942a785f002a03ade69

**Comment by christophs78** [comment]
> @christophs78 please code review this fix: [primefaces-extensions/primefaces-selenium@65ae2cf](https://github.com/primefaces-extensions/primefaces-selenium/commit/65ae2cf18c51011669600942a785f002a03ade69)

looks good!
