### ISSUE TITLE
Datatable: Selection with multiple with paging failing

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#71]
Datatable10Test: Selection with multiple with paging failing

Failing with:
```
 DataTable010Test.testSelectionMultipleWithPagingAndFilteringAndDelete:122->testSelectionMultipleWithPagingAndFiltering:114 expected: <1,3,5> but was: <1,5>
Error:    DataTable010Test.testSelectionMultipleWithPagingAndFiltering:114 expected: <1,3,5> but was: <1,5>
Error:    DataTable010Test.testSelectionMultipleWithPaging:70 expected: <1,2,5> but was: <1,5>
```

@christophs78 @tandraschko This broke this morning from the recent PF changes. I can't tell whether the new behavior is correct and the old test had the wrong results or the old test had the correct results and now its broken???

**Comment by tandraschko** [comment]
There weren't any DataTable changes?

**Comment by melloware** [comment]
Well this test was passing 14 hours ago and failed this morning so that is very strange. I can also verify it fails locally so its not an issue with out CI server.

**Comment by tandraschko** [comment]
i see. Sorry but dont have time to check it, i'm deep in the TreeTable thing.

**Comment by melloware** [comment]
No worries we will investigate.

**Comment by tandraschko** [comment]
maybe related to the StyleClassBuilder if some class is missing now?

**Comment by melloware** [comment]
Yep adding @Rapster to the ticket.

**Comment by tandraschko** [comment]
fixed something related to styleclasses

**Comment by melloware** [comment]
Thanks @tandraschko that fixed it!   These Integration tests are coming in very handy.

**Comment by christophs78** [comment]
Side-note: We are able to rerun Github Actions - job´s.
![image](https://user-images.githubusercontent.com/10461942/102102650-5d50ed80-3e2c-11eb-99e3-d08522b64bec.png)
IMO this should be our first choice if we are not sure wether our integration-test´s may have some kind of race-condition or there´s realy a issue with PrimeFaces itself. We can also use this to rerun a job after something was changed on the PrimeFaces-side without doing a dummy-commit in our integration-tests.
Overall - as said before - IMO integration-test´s are the only way to get a feature-monster like DataTable under control and reduce the amount of accidentially breaking things.
(Personally i currently still have to put much time and energy into my day-job. So currently i´m a bit quiet on the PrimeFaces-side of things.)

**Comment by tandraschko** [comment]
> 
> 
> Thanks @tandraschko that fixed it! These Integration tests are coming in very handy.

Yep thats true.

Thanks to both of you guys. I never had enough time to also introduce that many tests.

**Comment by Rapster** [comment]
Cheers to all of that. But one thing, wouldn't be easier to have ITs in PF repo and then create/update Github pipeline? This way it's automated no?

**Comment by christophs78** [comment]
> Cheers to all of that. But one thing, wouldn't be easier to have ITs in PF repo and then create/update Github pipeline? This way it's automated no?

Think so too. We may e.g. convert PrimeFaces into a multi module project. PrimeFaces (core) as one module, PrimeFaces Integrationtests as second module.
So our Integrationtests may run after each commit. Build would fail if integrationtests fail, ...

**Comment by tandraschko** [comment]
i asked several primetek several times for a multi-module project but no real answer... even the showcase could be in there and pf-selenium

**Comment by christophs78** [comment]
Maybe we can do this after 10 is released?
I could imagine PrimeTek has less knowledge of maven (or gradle) multi-module projects. So it´s hard for them to assess this. (I personally was a bit sceptic regarding multi-module a few years back too.)
So we may do a first step with integrating integration-tests as module a few weeks after 10.0 release when there is less project-activity. Do it right an convince PrimeTek this is a good thing.

**Comment by christophs78** [comment]
(Maybe Burak who seems to be a new member at PrimeTek has some more Java-background and is more open to such ideas. At least it looks like he is using IntelliJ.)

**Comment by tandraschko** [comment]
i will talk again to Cagatay after 10.
