### ISSUE TITLE
Check for JS console errors after each navigation

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-integration-tests#8]
We should also always check for JS errors on the console
maybe we can do it automatically after each navigation (we currently dont have a navigation-listener or simliar) or manually in each test (+ add method in primefaces-selenium like assertNoJavascriptErrors)

**Comment by melloware** [comment]
Great idea.

**Comment by tandraschko** [comment]
`    protected void assertNoJavascriptError() {
        LogEntries logEntries = getWebDriver().manage().logs().get(LogType.BROWSER);
        List<LogEntry> severe = logEntries.getAll().stream()
                .filter(l -> l.getLevel() == Level.SEVERE)
                .collect(Collectors.toList());
        Assertions.assertTrue(severe.isEmpty());
    }`

could be added to AbstractPrimePageTest atleast

**Comment by melloware** [comment]
I like it.  We could add another method if we wanted alled `debugConole` or `dumpConsole` that just printed out all console messages just if you wanted to check if antthing was bring printed out not just errors.

**Comment by melloware** [comment]
Added `assertNoJavascriptErrors` and `printConsole` methods to `AbstractPrimePageTest ` in 8.0.1
