### ISSUE TITLE
run integration-tests additional on MacOS + Safari

### ISSUE THREAD

**Issue by christophs78** [primefaces-extensions/primefaces-integration-tests#87]
https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners

We may run our tests on macos-latest instead/additional to ubuntu-latest.
And use Safari-Webdriver to run them against Safari additional to Chrome and Firefox.

**Comment by christophs78** [comment]
Safari (WebDriver) & Github Actions:
https://github.com/actions/virtual-environments/issues/91

**Comment by melloware** [comment]
This would be great!
